### PR TITLE
V8 Compatibility fix.

### PR DESCRIPTION
**Pull request by antgiant**
This is a super minor fix to allow this library to be compatible with the new and soon to be mandatory [V8 runtime](https://developers.google.com/apps-script/guides/v8-runtime/migration)

### CODE REVIEW

**Comment by airhadoken** [comment]
The Utilities.gs file is ported from https://github.com/gsuitedevs/apps-script-oauth1 and it would be better to just update that file wholesale from the source (it has two recent updates).

**Comment by antgiant** [comment]
Done. Utilities.gs is now a straight copy of https://github.com/gsuitedevs/apps-script-oauth1. Wish I had realized that earlier would have saved me some debugging. :-)

While I'm doing this should I update the other files from that project as well?

**Comment by airhadoken** [comment]
That would be the prudent thing to do but there's a huge caveat.  Some of the files from Google have customizations [EDIT: customization in this repo] to fix certain issues like percent encoding.  You'd either have to look at the diffs of Service.gs and Signer.gs against their corresponding versions for 2016 and reapply the changes, or try editing and applying the diffs from that repo against the files in this one.

If you're interested in doing that, I'll make you a collaborator on this project and I'll publish the edits in GAS so you can try them in developer mode before I make a release.

**Comment by antgiant** [comment]
Ok, so I have taken a solid look at this, and I think I'm willing to try. I went hunting and am pretty confident that I found all of your customizations to the parent repo. Turned out to be [smaller than I expected actually](https://github.com/airhadoken/twitter-lib/files/4335082/0001-Twitter_lib-Customization.patch.txt).

Here is my suggested path, which renders this pull irrelevant.

1. Update your copy of [apps-script-oauth1](https://github.com/airhadoken/apps-script-oauth1) to current and create a new branch called something like twitter_lib.
2. Add your copy of [apps-script-oauth1](https://github.com/airhadoken/apps-script-oauth1) (Branch twitter_lib) as a submodule to the [twitter_lib repo](https://github.com/airhadoken/twitter-lib).
3. Replace  `OAuth1.gs`, `Service.gs`, `Signer.gs`, & `Utilities.gs` with symlinks pointing to their home in the submodule.
4. Apply [attached patch](https://github.com/airhadoken/twitter-lib/files/4335082/0001-Twitter_lib-Customization.patch.txt) to the submodule and push it "upstream" (really to your own copy).

Then going forward all that will be required to incorporate new changes from the parent repo is 

1. to update your copy of [apps-script-oauth1](https://github.com/airhadoken/apps-script-oauth1) to current 
2. Rebase the twitter_lib branch onto master.
3. Update the submodule in the [twitter_lib repo](https://github.com/airhadoken/twitter-lib)

What are your thoughts on this approach?

**Comment by airhadoken** [comment]
Re the patch, for V8 I think we'd want to leave in the `typeof module...` lines, unless I'm missing something.  Other than that I think your approach is solid.

_waves magic wand__

Congratulations you are now a maintainer.

**Comment by antgiant** [comment]
Thanks!

My approach also requires that I can access your fork of apps-script-oauth1 unless you want me to make this project dependent on a fork I create of that repo.

As for the `typeof module...` lines. You had removed them so I left them out. I assumed because you have the TransientProperties module instead of that one. Happy to test leaving them in though.

**Comment by airhadoken** [comment]
Done and done.  I'll leave it to your discretion how to proceed from here.

The only thing that kept me from preferring MemoryProperties in the base fork over TransientProperties is that the TransientProperties constructor lets you pass in props at construction time.  This is still a difference between the two and I'd like to see that feature preserved, whether by a patch on MemoryProperties or wholesale replacing MemoryProperties with TransientProperties somehow in the submodule.

**Comment by antgiant** [comment]
Canceling this pull request as it is now superseded by the much better #29 .

**Pull request closed without merging**
