### PR TITLE
Added methods to chunk upload media files to Twitter

### LINKED ISSUE #6: Can uploadMedia() support chunked encoding for larger files?
@kfinley already tried to do this but gave up.  Maybe tinker with it if you're bored.

Synchronous execution is a definite problem here.  If media can't be uploaded in a timely manner the script will probably time out.

Building the perfect POST body is probably the biggest challenge.  Recall that trying to manually create the multipart/form-data block was frustrating (read: miserable failure) until you let the script engine do it automatically.  This is something completely not supported by fetch(), so it may be impossible, who knows.

### PR DESCRIPTION
**Pull request by manglaneso**
Should fix [issue 6](https://github.com/airhadoken/twitter-lib/issues/6). Should I add some code to show how it works? Let me know what you guys think.

### CODE REVIEW

**Comment by antgiant** [comment]
Sorry I missed this earlier. Adding to my list of things to test and possibly include.

**Review by antgiant — APPROVED** [review]
This looks good and is fully self contained. Merging in.

**Comment by antgiant** [comment]
v28 released now with this code included. Thanks again

**Comment by manglaneso** [comment]
Nice! Thanks for the merge approval!

**Pull request merged**
