### PR TITLE
Convert files from apps-script-oauth1 into submodule

### PR DESCRIPTION
**Pull request by antgiant**
And here are the updated files from #28 in action. I created my own testing copy of the library and successfully used this code to authorize a bot with twitter and send a tweet. Once this code is in the live library I'll be happy to repeat the test cycle.

### CODE REVIEW

**Comment by airhadoken** [comment]
It doesn't look like you pushed the referenced commit in apps-script-oauth1 yet.  (or at least, when I click the submodule link from the branch listing here in GH I get a 404)

**Comment by antgiant** [comment]
Oops sorry about that. Should work now.

**Comment by airhadoken** [comment]
OK, the updated service/signer/utilities/oauth1 files are on GAS so you can try them out in developer mode.

**Comment by antgiant** [comment]
Did you also make me an editor on GAS? It appears that [development mode only works for editors](https://developers.google.com/apps-script/guides/libraries#testing_and_debugging_your_library).

I did try it and got an identical error to before these changes were applied. To me that implies I'm not an editor and am still accessing the old code.

**Comment by airhadoken** [comment]
I had no idea that was a stipulation.  Can you request edit access on the script?  https://script.google.com/d/11dB74uW9VLpgvy1Ax3eBZ8J7as0ZrGtx4BPw7RKK-JQXyAJHBx98pY-7/edit?usp=sharing

**Comment by antgiant** [comment]
That did it!

Thank you!

I confirmed authorization and sending a tweet both worked without me changing anything once I had access to development mode.

You are welcome to roll back my access and create the official release, or I suppose I could now create the official release. Doesn't matter to me.

Oh, and I guess it should also be safe to enable V8 for the library, or just let Google do it whenever they decide to make it mandatory.

**Comment by airhadoken** [comment]
You can also decide if you want to include #27 into this release.  It's notable that in that PR thread I stated that I'm not really interested in further development against the Twitter API, which is why I'm looking for collaborators.  A community effort around maintaining the lib allows development to continue regardless of my personal feelings about the platform.

**Comment by antgiant** [comment]
In that case I'll see about including that. I will probably want to include a few additional items over time as well. Thanks again for granting me all this access!

**Comment by antgiant** [comment]
Twitter-lib Version 24 is now live with only this change (and the associated removal of the underscore library as it is no longer required). I looked into #27 and am going to save that for a future update.

Thanks again!

**Comment by airhadoken** [comment]
Time to update my pinned tweet then!

**Pull request merged**
